routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContractController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//http://kewangan.test/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function() {
    Route::get('contracts/{contract}/get-file',[ContractController::class, 'getFile'])
        ->name('contracts.download');
    Route::resource('contracts', 'ContractController')
        ->middleware('can:manage contracts');

    Route::resource('peranans', 'PerananController');
});

Route::get('/permissiontest', function() {
    // Pengguna menggunakan table user jadi ada data
    $pengguna = App\Pengguna::first();
    dump($pengguna->hasPermissionTo('guna modul 3'));
    dump($pengguna->hasPermissionTo('guna modul 2'));
    dd($pengguna->hasPermissionTo('guna modul 1'));
});

// //http://kewangan.test/contracts
    // Route::get('/contracts', [ContractController::class,'index'])
    //             ->name('contracts.index');
    // //http://kewangan.test/contracts

    // //paparkan form untuk isi data
    // Route::get('/contracts/create', [ContractController::class,'create'])
    //             ->name('contracts.create');
    // //submit data
    // Route::post('/contracts', [ContractController::class,'store'])
    //         ->name('contracts.store');

    // //http://kewangan.test/contracts/1
    // Route::get('/contracts/{contract}', [ContractController::class,'show'])
    //             ->name('contracts.show');
    // //http://kewangan.test/contracts/1/edit
    // Route::get('/contracts/{contract}/edit', [ContractController::class,'edit'])
    //             ->name('contracts.edit');
    // Route::put('/contracts/{contract}', [ContractController::class,'update'])
    //             ->name('contracts.update');
    // Route::delete('/contracts/{contract}', [ContractController::class,'destroy'])
    //             ->name('contracts.destroy');

app/Peranan.php
<?php

namespace App;

use Spatie\Permission\Models\Role;

class Peranan extends Role
{
    // perhatikan Peranan inherit daripada class Role Spatie
}

app/Http/Controllers/PerananController.php
<?php

namespace App\Http\Controllers;

use App\Peranan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Spatie\Permission\Models\Permission;

class PerananController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $search = request()->search;
        $perPage = request()->perPage;
        //abc comment me

        $peranans = Peranan::query()
            ->when($search, function ($query, $search) {
                return $query->where('name','LIKE', '%' . $search . '%')
                ;
            })
            ->paginate($perPage);

        // sampaikan data kepada view
        return view('peranan.index', compact(
                'peranans',
                'search',
                'perPage',
                )
            );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::orderBy('name')
            ->get();

        //paparkan form
        return view('peranan.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate data yg dihantar
        request()->validate([
            'name' => 'required|min:3',
        ]);

        //create rekod
        $peranan = new Peranan();
        //dapatkan data yg dihantar
        $peranan->name = request()->name;

        //save rekod
        $peranan->save();

        $peranan->syncPermissions(request()->permissions);

        //untuk notifikasi
        session()->flash('status', [
            'message' => __('Rekod berjaya disimpan'),
            'type' => 'success',
        ]);

        //redirect ke page index
        return redirect(route('peranans.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Peranan $peranan)
    {
        //paparkan
        return view('peranan.show', compact('peranan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Peranan $peranan)
    {
        $permissions = Permission::orderBy('name')
            ->get();

        // paparkan form dengan peranan
        return view('peranan.edit', compact('peranan', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Peranan $peranan)
    {
        //validate data yg dihantar
        request()->validate([
            'name' => 'required|min:3',
        ]);

        // dapatkan rekod dihantar
        $peranan->name = request()->name;
        // save peranan
        $peranan->save();

        $peranan->syncPermissions(request()->permissions);

        //untuk notifikasi
        session()->flash('status', [
            'message' => __('Rekod berjaya dikemaskini'),
            'type' => 'success',
        ]);

        //redirect ke page index
        return redirect(route('peranans.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Peranan $peranan)
    {
        $peranan->delete();

        //untuk notifikasi
        session()->flash('status', [
            'message' => __('Rekod berjaya dibuang'),
            'type' => 'success',
        ]);

        //redirect ke page index
        return redirect(route('peranans.index'));
    }
}

resources/views/peranan/create.blade.php
@extends('layouts.app')

@section('content')

<form action="{{ route('contracts.store') }}" method="POST"
    enctype='multipart/form-data'
>
  @csrf
  <div class="form-group">
    <label for="name">Nama</label>
    <input type="text"
        class="form-control"
        id="name"
        name="name"
        aria-describedby="nameHelp">
    <small id="nameHelp"
        class="form-text text-muted">Catatan contract
    </small>
    @error('name')
        <div class="alert alert-danger">{{ $message }}</div>
    @enderror
  </div>
    {{ dump($peranan->permissions) }}
  @foreach($permissions as $permission)
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="permission_{{ $permission->id }}">
        <label class="form-check-label" for="permission_{{ $permission->id }}"
            value="{{ $permission->id }}"
            name="permissions[{{ $permission->id }}]"
        >
            {{ $permission->name }}
        </label>
    </div>
  @endforeach


  <input type="text"
        class="form-control"
        name="extra[]"
        aria-describedby="nameHelp">
        <input type="text"
        class="form-control"
        name="extra[]"
        aria-describedby="nameHelp">
        <input type="text"
        class="form-control"
        name="extra[]"
        aria-describedby="nameHelp">

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

@endsection

resources/views/peranan/edit.blade.php
@extends('layouts.app')

@section('content')

<form action="{{ route('peranans.update', $peranan->id) }}" method="POST">
  @csrf
  @method('PUT')
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text"
        class="form-control"
        id="name"
        name="name"
        value="{{ old('name', $peranan->name) }}"
        aria-describedby="nameHelp">
    <small id="nameHelp"
        class="form-text text-muted">Nama
    </small>
    @error('name')
        <div class="alert alert-danger">{{ $message }}</div>
    @enderror
  </div>

    @foreach($permissions as $permission)
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" id="permission_{{ $permission->id }}"
                   value="{{ $permission->id }}"
                   name="permissions[{{ $permission->id }}]"
                   @if($peranan->hasPermissionTo($permission)) checked @endif
            >
            <label class="form-check-label" for="permission_{{ $permission->id }}">
                {{ $permission->name }}
            </label>
        </div>
    @endforeach

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

@endsection

resources/views/peranan/index.blade.php
@extends('layouts.app')

@section('content')
<h1>Peranan</h1>
<div class="rows">
    <form method="GET">
        <div class="col-6">
          <div class="form-group">
            <input type="text"
                class="form-control"
                name="search"
                value="{{ $search }}"
                placeholder="Search..."
                >
          </div>
        </div>
        <div class="col-3">
          <div class="form-group">
            <input type="text"
                class="form-control"
                name="perPage"
                value="{{ $perPage }}"
                placeholder="Perpage"
                >
          </div>
        </div>
        <div class="col-3">
          <div class="form-group">
            <button class="btn btn-primary">Cari</button>
          </div>
        </div>
    </form>
</div>

<a href="{{ route('peranans.create') }}"
    class="btn btn-primary btn-sm"
> New Role </a>

<table class="table table-stripe">
    <tr>
        <th>Name</th>
        <th></th>
    </tr>
    @foreach($peranans as $peranan)
        <tr>
            <td>{{ $peranan->name }}</td>
            <td>
                <a href="{{ route('peranans.show', $peranan->id) }}"
                    class="btn btn-primary btn-sm"
                > View </a>

                @can('update contract')
                    <a href="{{ route('peranans.edit', $peranan->id) }}"
                        class="btn btn-primary btn-sm"
                    > Edit </a>
                @endcan
                @can('delete contract')
                    <a class="btn btn-danger btn-sm" href=""
                       onclick="event.preventDefault();
                                     document.getElementById('kewangan_delete_{{ $peranan->id }}').submit();">
                        {{ __('Padam') }}
                    </a>

                    <form id="kewangan_delete_{{ $peranan->id }}"
                        action="{{ route('peranans.destroy', $peranan) }}"
                        method="POST" class="d-none">
                        @csrf
                        @method('DELETE')
                    </form>
                @endcan
            </td>
        </tr>
    @endforeach
</table>
{{ $peranans->links() }}
@endsection

resources/views/peranan/show.blade.php
@extends('layouts.app')

@section('content')

<table class="table">
    <tr>
        <th>Name:</th>
        <td>{{ $peranan->name }}</td>
    </tr>
    <tr>
        <td>Permissions</td>
        <td>
            @foreach($peranan->permissions as $permission)
                {{ $permission->name }}<br>
            @endforeach
        </td>
    </tr>
</table>

@endsection