routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ContractController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//http://kewangan.test/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function() {
    Route::get('contracts/{contract}/get-file',[ContractController::class, 'getFile'])
        ->name('contracts.download');
    Route::resource('contracts', 'ContractController')
        ->middleware('can:manage contracts');

    Route::resource('peranans', 'PerananController');
});

Route::get('/permissiontest', function() {
    // Pengguna menggunakan table user jadi ada data
    $pengguna = App\Pengguna::first();
    dump($pengguna->hasPermissionTo('guna modul 3'));
    dump($pengguna->hasPermissionTo('guna modul 2'));
    dd($pengguna->hasPermissionTo('guna modul 1'));
});

// //http://kewangan.test/contracts
    // Route::get('/contracts', [ContractController::class,'index'])
    //             ->name('contracts.index');
    // //http://kewangan.test/contracts

    // //paparkan form untuk isi data
    // Route::get('/contracts/create', [ContractController::class,'create'])
    //             ->name('contracts.create');
    // //submit data
    // Route::post('/contracts', [ContractController::class,'store'])
    //         ->name('contracts.store');

    // //http://kewangan.test/contracts/1
    // Route::get('/contracts/{contract}', [ContractController::class,'show'])
    //             ->name('contracts.show');
    // //http://kewangan.test/contracts/1/edit
    // Route::get('/contracts/{contract}/edit', [ContractController::class,'edit'])
    //             ->name('contracts.edit');
    // Route::put('/contracts/{contract}', [ContractController::class,'update'])
    //             ->name('contracts.update');
    // Route::delete('/contracts/{contract}', [ContractController::class,'destroy'])
    //             ->name('contracts.destroy');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('contracts.index') }}">{{ __('Contracts') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('peranans.index') }}">{{ __('Peranan/Roles') }}</a>
                            </li>
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="container">
            @if( session()->has('status') )
                <div class="alert
                    alert-{{ session('status')['type'] }}
                    alert-dismissible fade show" role="alert"
                    >
                    {{ session('status')['message'] }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
            @endif
            @yield('content')
        </main>
    </div>
</body>
</html>